### ISSUE TITLE
Could you please update your ReadMe file?

### ISSUE THREAD

**Issue by RegisWang** [BigRedT/DTAM#1]
Hi, 

Thanks for sharing your code. There is a big difference between your code and OpenDTAM. So, could you please update your ReadMe file to explain a little how to compile it and how make it works?

BR
Regis

**Comment by BigRedT** [comment]
I cloned OpenDTAM to try to get it to work with my own video sequence, but I couldn't get it to work it on anything except the sequence provided with the code. So currently I am using LSD-SLAM for obtaining camera poses and then using my own implementation of a variant of DTAM's cost volume optimization for generating the dense depth maps. This work is unpublished yet but I will release the code as soon as it is published.
